#!/bin/bash

echo "🔧 Guia para Verificar Configurações FTP na Hostinger"
echo "=================================================="
echo ""
echo "📋 PASSO A PASSO:"
echo "1. Acesse o painel da Hostinger (hpanel.hostinger.com)"
echo "2. Vá para 'Files' → 'FTP Accounts'"
echo "3. Procure pelas seguintes informações:"
echo ""
echo "🔍 INFORMAÇÕES NECESSÁRIAS:"
echo "   ├── Host/Server: (exemplo: files.000webhost.com ou IP)"
echo "   ├── Username: u116045488.giselegalvao"
echo "   ├── Port: (geralmente 21 para FTP ou 22 para SFTP)"
echo "   ├── Protocol: FTP, FTPS ou SFTP"
echo "   └── Directory: /public_html/ ou /domains/giselegalvao.com.br/public_html/"
echo ""
echo "⚙️ CONFIGURAÇÕES COMUNS DA HOSTINGER:"
echo "   • Server: files.000webhost.com (contas gratuitas)"
echo "   • Server: seu-dominio.com (contas pagas)"
echo "   • Server: IP específico (ex: 185.158.133.1)"
echo "   • Port: 21 (FTP) ou 22 (SFTP)"
echo "   • Protocol: FTP, FTPS ou SFTP"
echo ""
echo "🚨 PROBLEMAS COMUNS:"
echo "   1. Timeout Error: Servidor ou porta incorretos"
echo "   2. Authentication Failed: Username/password incorretos"
echo "   3. SFTP vs FTP: Hostinger pode usar SFTP em vez de FTP"
echo "   4. Firewall: Algumas redes bloqueiam FTP (porta 21)"
echo ""
echo "💡 SOLUÇÕES:"
echo "   • Tente SFTP (porta 22) em vez de FTP (porta 21)"
echo "   • Verifique se a conta FTP está ativa no painel"
echo "   • Confirme se o password está correto no GitHub Secrets"
echo "   • Use o hostname fornecido pela Hostinger"
echo ""
echo "🔗 TESTES MANUAIS:"
echo "   Para testar FTP via terminal:"
echo "   ftp giselegalvao.com.br"
echo "   (ou o server fornecido pela Hostinger)"
echo ""
echo "   Para testar SFTP via terminal:"
echo "   sftp u116045488.giselegalvao@giselegalvao.com.br"
echo ""
echo "📝 PRÓXIMOS PASSOS:"
echo "1. Verifique as configurações no painel da Hostinger"
echo "2. Atualize o workflow com as informações corretas"
echo "3. Teste o deploy novamente"
